name: Build and Push to registry

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: build and push docker image
        run: |
          docker login --username KamoheloKoali --password ${{ secrets.CR_PAT }} ghcr.io
          docker build . --tag ghcr.io/kamohelokoali/learning_workflows:latest
          docker push ghcr.io/kamohelokoali/learning_workflows:latest
